# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
jobs:
  Test:
    runs-on: Windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - name: Before symlink patch
      working-directory: .\test
      run: actualBehavior.cmd
    - name: After symlink patch
      working-directory: .\test
      run: expectedBehavior.cmd